#define PIN_ENA 4
#define PIN_DIR 5
#define PIN_PUL 11

#define STEP_PER_TURNAROUND 3200

#define FIRST_TUBE_SENSOR_PIN 8
#define TUBE_CENTER_SENSOR_PIN 9

#define PUSHER_FIRST_SERVO_PIN 2
#define PUSHER_SECOND_SERVO_PIN 3

#define CAP_FIRST_SERVO_PIN 6
#define CAP_SECOND_SERVO_PIN 7

#define SERVICE_DOOR_SENSOR_PIN 10
#define SERVICE_LEFT_ROTATE_BUTTON 12
#define SERVICE_RIGHT_ROTATE_BUTTON 13